### ISSUE TITLE
Add a `OrganizationIPAddress` model

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-db-activerecord#84]
Add a `OrganizationIPAddress` join model for associating a `IPAddress` with an `Organization`.

**Comment by rakshit087** [comment]
Can you assign this to me? Would be happy to contribute.

**Comment by postmodern** [comment]
@rakshit087 this issue is already assigned to me.

**Comment by postmodern** [comment]
Implemented in 2804e04.
