### ISSUE TITLE
Add a `PersonalPhoneNumber` model

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-db-activerecord#97]
Add a `PersonalPhoneNumber` model that associates a `PhoneNumber` with a `Person`.

**Comment by adarsh-jha-dev** [comment]
Hey @postmodern , could you please assign this issue to me too?

**Comment by postmodern** [comment]
@adarsh-jha-dev this issue is already assigned to me *and* marked as In Progress; I already have the file written.

**Comment by adarsh-jha-dev** [comment]
> @adarsh-jha-dev this issue is already assigned to me _and_ marked as In Progress; I already have the file written.

Ok Ok, no issues

**Comment by postmodern** [comment]
Implemented in 204e8d1 and merged into the `0.2.0` branch.
